# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do

  desc "Description of what the lane does"
  lane :build_archive do
    scan
    build_mac_app
    clear_derived_data
    notification(subtitle: "Finished Building", message: "Ready to upload...")
  end

  desc "Run linting"
  lane :lint do

    swiftlint(
      mode: :lint,
      strict: true,
      config_file: '.swiftlint.yml',
      reporter: "codeclimate",
      ignore_exit_status: true,
      output_file: "fastlane/codequality_report.json"
    )
  end
end
